### ISSUE TITLE
git doesn't successfully install in image (drake_v2)

### ISSUE THREAD

**Issue by karthikurs** [kwesiRutledge/OzayGroupExploration#1]
```E: Package 'git' has no installation candidate
The command '/bin/sh -c apt --yes install git' returned a non-zero code: 100
```

Solution:
Add the following lines to the Dockerfile:
```
apt-get update
apt-get --yes install git
```

This change installs git via `apt-get` instead of `apt` which solves the problem.

**Comment by kwesiRutledge** [comment]
Thanks for catching this, Karthik! I've updated two of the `Dockerfile` files to use `apt-get` instead of `git`. The updates should be present in this commit [[06fd6a68c4b3a7670a1826f2e2edd1e17438191a](https://github.com/kwesiRutledge/OzayGroupExploration/commit/06fd6a68c4b3a7670a1826f2e2edd1e17438191a)].
